import { PrismaClient, Role } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  const users = [
    {
      nama_petugas: "Admin Utama",
      email: "admin@example.com",
      password: "admin123",
      role: Role.ADMIN,
      foto_profil: null,
      alamat: "Jl. Admin No. 1, Jakarta",
      no_telp: "081234567890",
      nama_vendor: null, // kosong untuk admin
      verified_at: new Date(), // admin sudah terverifikasi
      verified_by: "SYSTEM",
    },
    {
      nama_petugas: "Verifier Utama",
      email: "verifier@example.com",
      password: "verifier123",
      role: Role.VERIFIER,
      foto_profil: null,
      alamat: "Jl. Verifier No. 2, Jakarta",
      no_telp: "081234567891",
      nama_vendor: null, // kosong untuk verifier
      verified_at: new Date(), // verifier sudah terverifikasi
      verified_by: "ADMIN",
    },
    {
      nama_petugas: "Verifier Kedua",
      email: "verifier2@example.com",
      password: "verifier123",
      role: Role.VERIFIER,
      foto_profil: null,
      alamat: "Jl. Verifier No. 3, Bandung",
      no_telp: "081234567899",
      nama_vendor: null, // kosong untuk verifier
      verified_at: new Date(), // verifier sudah terverifikasi
      verified_by: "ADMIN",
    },
    // 20 Vendor Dummy Data
    {
      nama_petugas: "Budi Santoso",
      email: "budi@vendor1.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Mangga No. 1, Jakarta Selatan",
      no_telp: "081234567801",
      nama_vendor: "CV Budi Jaya",
      verified_at: new Date(),
      verified_by: "Verifier Utama",
    },
    {
      nama_petugas: "Siti Rahayu",
      email: "siti@vendor2.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Jeruk No. 15, Bandung",
      no_telp: "081234567802",
      nama_vendor: "PT Siti Makmur",
      verified_at: null,
      verified_by: null,
    },
    {
      nama_petugas: "Ahmad Fauzi",
      email: "ahmad@vendor3.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Apel No. 7, Surabaya",
      no_telp: "081234567803",
      nama_vendor: "UD Ahmad Sejahtera",
      verified_at: new Date(),
      verified_by: "Verifier Kedua",
    },
    {
      nama_petugas: "Dewi Lestari",
      email: "dewi@vendor4.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Melati No. 12, Yogyakarta",
      no_telp: "081234567804",
      nama_vendor: "CV Dewi Indah",
      verified_at: new Date(),
      verified_by: "Verifier Utama",
    },
    {
      nama_petugas: "Eko Prasetyo",
      email: "eko@vendor5.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Mawar No. 5, Semarang",
      no_telp: "081234567805",
      nama_vendor: "PT Eko Global",
      verified_at: null,
      verified_by: null,
    },
    {
      nama_petugas: "Rina Susanti",
      email: "rina@vendor6.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Anggrek No. 8, Medan",
      no_telp: "081234567806",
      nama_vendor: "CV Rina Mandiri",
      verified_at: new Date(),
      verified_by: "Verifier Kedua",
    },
    {
      nama_petugas: "Joko Widodo",
      email: "joko@vendor7.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Kenanga No. 3, Solo",
      no_telp: "081234567807",
      nama_vendor: "UD Joko Sukses",
      verified_at: new Date(),
      verified_by: "Verifier Utama",
    },
    {
      nama_petugas: "Maya Sari",
      email: "maya@vendor8.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Tulip No. 20, Malang",
      no_telp: "081234567808",
      nama_vendor: "PT Maya Berkah",
      verified_at: null,
      verified_by: null,
    },
    {
      nama_petugas: "Rudi Hartono",
      email: "rudi@vendor9.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Dahlia No. 11, Palembang",
      no_telp: "081234567809",
      nama_vendor: "CV Rudi Abadi",
      verified_at: new Date(),
      verified_by: "Verifier Kedua",
    },
    {
      nama_petugas: "Lina Marlina",
      email: "lina@vendor10.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Cempaka No. 6, Makassar",
      no_telp: "081234567810",
      nama_vendor: "UD Lina Jaya",
      verified_at: new Date(),
      verified_by: "Verifier Utama",
    },
    {
      nama_petugas: "Hendra Wijaya",
      email: "hendra@vendor11.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Sakura No. 14, Denpasar",
      no_telp: "081234567811",
      nama_vendor: "PT Hendra Prima",
      verified_at: null,
      verified_by: null,
    },
    {
      nama_petugas: "Putri Ayu",
      email: "putri@vendor12.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Flamboyan No. 9, Balikpapan",
      no_telp: "081234567812",
      nama_vendor: "CV Putri Cemerlang",
      verified_at: new Date(),
      verified_by: "Verifier Kedua",
    },
    {
      nama_petugas: "Wahyu Nugroho",
      email: "wahyu@vendor13.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Bougenville No. 18, Pontianak",
      no_telp: "081234567813",
      nama_vendor: "UD Wahyu Maju",
      verified_at: new Date(),
      verified_by: "Verifier Utama",
    },
    {
      nama_petugas: "Indira Sari",
      email: "indira@vendor14.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Kamboja No. 2, Pekanbaru",
      no_telp: "081234567814",
      nama_vendor: "PT Indira Sejati",
      verified_at: null,
      verified_by: null,
    },
    {
      nama_petugas: "Bambang Sutrisno",
      email: "bambang@vendor15.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Teratai No. 16, Jambi",
      no_telp: "081234567815",
      nama_vendor: "CV Bambang Makmur",
      verified_at: new Date(),
      verified_by: "Verifier Kedua",
    },
    {
      nama_petugas: "Tri Wulandari",
      email: "tri@vendor16.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Gardenia No. 4, Padang",
      no_telp: "081234567816",
      nama_vendor: "UD Tri Sukses",
      verified_at: new Date(),
      verified_by: "Verifier Utama",
    },
    {
      nama_petugas: "Fajar Nugraha",
      email: "fajar@vendor17.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Lavender No. 13, Banjarmasin",
      no_telp: "081234567817",
      nama_vendor: "PT Fajar Gemilang",
      verified_at: null,
      verified_by: null,
    },
    {
      nama_petugas: "Sari Dewi",
      email: "sari@vendor18.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Peony No. 10, Manado",
      no_telp: "081234567818",
      nama_vendor: "CV Sari Utama",
      verified_at: new Date(),
      verified_by: "Verifier Kedua",
    },
    {
      nama_petugas: "Agus Setiawan",
      email: "agus@vendor19.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Iris No. 17, Banda Aceh",
      no_telp: "081234567819",
      nama_vendor: "UD Agus Berkah",
      verified_at: new Date(),
      verified_by: "Verifier Utama",
    },
    {
      nama_petugas: "Mega Putri",
      email: "mega@vendor20.com",
      password: "vendor123",
      role: Role.VENDOR,
      foto_profil: null,
      alamat: "Jl. Violet No. 19, Jayapura",
      no_telp: "081234567820",
      nama_vendor: "PT Mega Sukses",
      verified_at: null,
      verified_by: null,
    },
  ];

  for (const user of users) {
    const hashedPassword = await bcrypt.hash(user.password, 10);

    await prisma.user.upsert({
      where: { email: user.email },
      update: {}, // tidak update kalau sudah ada
      create: {
        nama_petugas: user.nama_petugas,
        email: user.email,
        password: hashedPassword,
        role: user.role,
        foto_profil: user.foto_profil,
        alamat: user.alamat,
        no_telp: user.no_telp,
        nama_vendor: user.nama_vendor,
        verified_at: user.verified_at,
        verified_by: user.verified_by,
      },
    });
  }

  console.log("✅ Seeding selesai");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
